/// Flutter icons ProfileCustomIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ProfileCustomIcons
///      fonts:
///       - asset: fonts/ProfileCustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ProfileCustomIcons {
  ProfileCustomIcons._();

  static const _kFontFam = 'ProfileCustomIcons';
  static const String? _kFontPkg = null;

  static const IconData wishlist = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addresses = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orders = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopcon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
