/// Flutter icons Appbar
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Appbar
///      fonts:
///       - asset: fonts/Appbar.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
///
import 'package:flutter/widgets.dart';

class CustomAppbar {
  CustomAppbar._();

  static const _kFontFam = 'Appbar';
  static const String? _kFontPkg = null;

  static const IconData location = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
